#pragma once

#define VIAL_KEYBOARD_UID { 0x69, 0x53, 0xE5, 0xBB, 0x33, 0x42, 0x95, 0xC0 }

#define VIAL_TAP_DANCE_ENTRIES 8
#define VIAL_COMBO_ENTRIES 8
#define VIAL_KEY_OVERRIDE_ENTRIES 8
#define DYNAMIC_KEYMAP_MACRO_COUNT 8

#define VIAL_UNLOCK_COMBO_COLS { 0 }
#define VIAL_UNLOCK_COMBO_ROWS { 0 }
