RGB_MATRIX_ENABLE = yes
ENCODER_MAP_ENABLE = yes


# OLED_ENABLE = yes
# OLED_DRIVER = ssd1306
# OLED_TRANSPORT = i2c


VIA_ENABLE = yes
VIAL_ENABLE = yes
# VIAL_INSECURE = yes
VIALRGB_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes
